<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-13T20:37:14 IST" name="Suite" finished-at="2025-06-13T20:37:37 IST" duration-ms="23392">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.LogInErrorValidation()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" name="LogInErrorValidation" class="Automation.Framework.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="StandaloneTest2.Standalone(java.util.HashMap)[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" name="Standalone" class="Automation.Framework.StandaloneTest2"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-06-13T20:37:14 IST" name="Base Test" finished-at="2025-06-13T20:37:14 IST" duration-ms="26">
    </test> <!-- Base Test -->
    <test started-at="2025-06-13T20:37:14 IST" name="Error Validation Test" finished-at="2025-06-13T20:37:23 IST" duration-ms="9546">
      <class name="Automation.Framework.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:14 IST" name="launchApplication" finished-at="2025-06-13T20:37:19 IST" duration-ms="5519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LogInErrorValidation()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:19 IST" name="LogInErrorValidation" finished-at="2025-06-13T20:37:20 IST" duration-ms="398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogInErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:20 IST" name="tearDown" finished-at="2025-06-13T20:37:20 IST" duration-ms="98" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:20 IST" name="launchApplication" finished-at="2025-06-13T20:37:21 IST" duration-ms="1090" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:21 IST" name="ProductErrorValidation" finished-at="2025-06-13T20:37:23 IST" duration-ms="2005" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at Automation.Framework.ErrorValidations.ProductErrorValidation(ErrorValidations.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Framework.ErrorValidations@461ad730]" started-at="2025-06-13T20:37:23 IST" name="tearDown" finished-at="2025-06-13T20:37:23 IST" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Automation.Framework.ErrorValidations -->
    </test> <!-- Error Validation Test -->
    <test started-at="2025-06-13T20:37:14 IST" name="Submit Order Test" finished-at="2025-06-13T20:37:37 IST" duration-ms="23392">
      <class name="Automation.Framework.StandaloneTest2">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:14 IST" name="launchApplication" finished-at="2025-06-13T20:37:21 IST" duration-ms="6816" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="Standalone(java.util.HashMap)[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:21 IST" name="Standalone" data-provider="getData" finished-at="2025-06-13T20:37:24 IST" duration-ms="2725" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Xoon@2364136, email=hb@outlook.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Standalone -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:24 IST" name="tearDown" finished-at="2025-06-13T20:37:24 IST" duration-ms="104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:24 IST" name="launchApplication" finished-at="2025-06-13T20:37:25 IST" duration-ms="1162" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="Standalone(java.util.HashMap)[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:25 IST" name="Standalone" data-provider="getData" finished-at="2025-06-13T20:37:37 IST" duration-ms="11720" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, email=anshika@gmail.com, productName=ADDIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Automation.Framework.StandaloneTest2.Standalone(StandaloneTest2.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Standalone -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Automation.Framework.StandaloneTest2@7a6d7e92]" started-at="2025-06-13T20:37:37 IST" name="tearDown" finished-at="2025-06-13T20:37:37 IST" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Automation.Framework.StandaloneTest2 -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
